name: Flutter Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # 릴리즈 생성을 위해 쓰기 권한 명시

jobs:
  build:
    name: Build, Test and Release APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Clean pubspec.lock
        run: rm -f pubspec.lock

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Generate App Icons
        run: dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release --build-number=${{ github.run_number }}

      - name: Check Build Artifacts
        run: |
          ls -R build/app/outputs/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/*.apk
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
